---
baseurl: "https://kennyballou.com"
MetaDataFormat: "yaml"
languageCode: "en-us"
title: "~kballou"
indexes:
  tag: "tags"
  topic: "topics"
permalinks:
  blog: /blog/:year/:month/:slug
copyright: "Creative Commons Attribution"
author:
  name: "Kenny Ballou"
...
